### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by aloksingh3112** [explooosion/Agm-Direction-Docs#1]
Not able  install this module with AGM core module

**Comment by explooosion** [comment]
I’m not sure I understand what you mean.

```bash
npm install --save @agm/core
npm install --save agm-direction
```

**Comment by aloksingh3112** [comment]
when ever i installed agm-direction 
![untitled](https://user-images.githubusercontent.com/27079355/46547155-be91e380-c8e8-11e8-9626-42764f44c8ea.jpg)

**Comment by aloksingh3112** [comment]
whenever i install agm-direction i always get this error 
![untitled](https://user-images.githubusercontent.com/27079355/46547364-542d7300-c8e9-11e8-971c-09eb1a36e1a8.jpg)

**Comment by aloksingh3112** [comment]
I got reference error that agm-direction is not a module whenever I installed it by typing
 npm install --save agm-direction

but when I add @latest it gets fixed

**Comment by explooosion** [comment]
agm-direction is an independent package.
[The official modules](https://github.com/SebastianM/angular-google-maps) do not include agm-direction.

The latest version of agm-direction is ```0.7.3``` .

Maybe your package-lock.json locked the old version.
Please check out package.json or removing package-lock.json. 🤔

Thank you for reporting.🙂
