### ISSUE TITLE
unable to draw international flights path

### ISSUE THREAD

**Issue by Affan93** [explooosion/Agm-Direction-Docs#2]
Hi!
I am trying to create path for international flights. but unable to pull that off. not sure what's going wrong. it just show the empty map. no location point nothing

> `<agm-map [latitude]="lat" [longitude]="lng">
  <agm-direction [origin]="origin" [destination]="destination" [travelMode]="travelMode"></agm-direction>
</agm-map>`

>`
@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  name = 'Angular 7'

  lat: Number = 24.799448
  lng: Number = 120.979021

  origin = { lat: 24.799448, lng: 120.979021 }
  destination = { lat: 56.1304, lng: 106.3468 }
  public travelMode: string = 'Flights'

}
`

**Comment by explooosion** [comment]
Sorry, I didn't find Airplane mode.

I’m not sure I get your meaning.  

Ref
- [directions#TravelMode](https://developers.google.com/maps/documentation/javascript/reference/directions#TravelMode)
- [How to set travel mode to “Flight” in google map direction API .
](https://stackoverflow.com/questions/35502261/how-to-set-travel-mode-to-flight-in-google-map-direction-api)
