### ISSUE TITLE
Edit MyPanel

### ISSUE THREAD

**Issue by luciano1997** [explooosion/Agm-Direction-Docs#8]
how can i set the information of MyPanel ?
i just need to see the interconnections of my waypoints

now it looks like this
![image](https://user-images.githubusercontent.com/43941133/93909306-04af0000-fcd6-11ea-93ed-6c8d5c40bed8.png)

but i need it to look like this

![image](https://user-images.githubusercontent.com/43941133/93909696-68392d80-fcd6-11ea-9c31-a4ed2bae0b4d.png)

Thanks

**Comment by explooosion** [comment]
Hi @luciano1997 

How do you use google map api to modify the style in the picture?

**Comment by explooosion** [comment]
In fact, I still need to use google map api to do it

**Comment by explooosion** [comment]
Hi @luciano1997 

Here is my way to use css.
setPanelStyle is a recursive function. 
This function should use setTimeout to avoid zonejs error (Maximum call stack size exceeded).

HTML

```html
<agm-map ...>
  <agm-direction
    ...
   [panel]="myPanel"
   (onChange)="onChange($event)"
   >
  </agm-direction>
</agm-map>
<div id="myPanel" #myPanel></div>
```

TS

```ts
onChange(): void {
  this.setPanelStyle();
}

setPanelStyle(): void {
  setTimeout(() => {
    if (document.querySelector('#myPanel').hasChildNodes()) {
      document.querySelectorAll('#myPanel .adp .adp-summary + div')
        .forEach((div: HTMLElement) => div.style.display = 'none');
    } else {
      this.setPanelStyle();
    }
  }, 1);
}
```

### Ref

- https://stackoverflow.com/questions/18954463/modifying-google-maps-default-directions-title

**Comment by luciano1997** [comment]
Thank you very much, yesterday reviewing the questions I found that someone else recommended to use (onChange) = "onChange ($ event), I will try with the code you shared !, Thanks for answering
